// Stage 5: Nutrition Database Lookup Service
// Decoupled from vision recognition. Sources data from NIN (National Institute of Nutrition, India) & USDA.

export const NUTRITION_DATABASE = [
  // 1. Traditional Snacks & Savories
  {
    name: 'Boondi',
    alternateNames: ['Bonde', 'Kara Boondi', 'Crispy Boondi', 'Khara Boondi', 'Boondi Mixture'],
    category: 'snack',
    standardUnit: 'bowl (50g)',
    calories: 240,
    protein_g: 5.5,
    carbohydrates_g: 28.0,
    fat_g: 12.0,
    fiber_g: 2.5,
    sugar_g: 0.5,
    sodium_mg: 240,
    isVeg: true,
  },
  {
    name: 'Boondi Raita',
    alternateNames: ['Bonde Raita', 'Dahi Boondi'],
    category: 'dairy',
    standardUnit: 'bowl (150g)',
    calories: 160,
    protein_g: 6.2,
    carbohydrates_g: 14.0,
    fat_g: 8.5,
    fiber_g: 1.2,
    sugar_g: 3.5,
    sodium_mg: 180,
    isVeg: true,
  },
  {
    name: 'Sweet Boondi',
    alternateNames: ['Meethi Boondi'],
    category: 'sweet',
    standardUnit: 'serving (50g)',
    calories: 210,
    protein_g: 3.5,
    carbohydrates_g: 36.0,
    fat_g: 6.0,
    fiber_g: 1.0,
    sugar_g: 28.0,
    sodium_mg: 40,
    isVeg: true,
  },
  {
    name: 'Boondi Laddu',
    alternateNames: ['Motichoor Laddu', 'Boondi Ladoo'],
    category: 'sweet',
    standardUnit: 'piece (40g)',
    calories: 185,
    protein_g: 3.0,
    carbohydrates_g: 26.0,
    fat_g: 8.0,
    fiber_g: 1.0,
    sugar_g: 22.0,
    sodium_mg: 30,
    isVeg: true,
  },
  {
    name: 'Samosa',
    alternateNames: ['Potato Samosa', 'Aloo Samosa'],
    category: 'snack',
    standardUnit: 'piece (80g)',
    calories: 220,
    protein_g: 4.5,
    carbohydrates_g: 26.0,
    fat_g: 11.0,
    fiber_g: 3.0,
    sugar_g: 1.5,
    sodium_mg: 280,
    isVeg: true,
  },
  {
    name: 'Pakoda',
    alternateNames: ['Pakora', 'Bhajiya', 'Onion Pakoda'],
    category: 'snack',
    standardUnit: 'serving (100g)',
    calories: 280,
    protein_g: 6.0,
    carbohydrates_g: 28.0,
    fat_g: 16.0,
    fiber_g: 3.5,
    sugar_g: 2.0,
    sodium_mg: 320,
    isVeg: true,
  },
  {
    name: 'Murukku',
    alternateNames: ['Chakli', 'Chakkuli'],
    category: 'snack',
    standardUnit: 'piece (30g)',
    calories: 150,
    protein_g: 2.5,
    carbohydrates_g: 18.0,
    fat_g: 7.5,
    fiber_g: 1.5,
    sugar_g: 0.2,
    sodium_mg: 160,
    isVeg: true,
  },
  {
    name: 'Roasted Makhana',
    alternateNames: ['Fox Nuts', 'Phool Makhana'],
    category: 'snack',
    standardUnit: 'bowl (30g)',
    calories: 105,
    protein_g: 3.2,
    carbohydrates_g: 20.0,
    fat_g: 1.5,
    fiber_g: 2.5,
    sugar_g: 0.2,
    sodium_mg: 70,
    isVeg: true,
  },

  // 2. Breakfast Specialties
  {
    name: 'Dosa',
    alternateNames: ['Crispy Plain Dosa', 'Plain Dosa', 'Dosha', 'Sada Dosa'],
    category: 'breakfast',
    standardUnit: '1 dosa',
    calories: 170,
    protein_g: 4.0,
    carbohydrates_g: 28.0,
    fat_g: 5.0,
    fiber_g: 1.5,
    sugar_g: 0.5,
    sodium_mg: 190,
    isVeg: true,
  },
  {
    name: 'Masala Dosa',
    alternateNames: ['Masala Dosa with Sambar & Chutney'],
    category: 'breakfast',
    standardUnit: '1 dosa',
    calories: 285,
    protein_g: 6.5,
    carbohydrates_g: 44.0,
    fat_g: 9.5,
    fiber_g: 3.8,
    sugar_g: 1.5,
    sodium_mg: 340,
    isVeg: true,
  },
  {
    name: 'Ragi Dosa',
    alternateNames: ['Finger Millet Dosa', 'Nachni Dosa'],
    category: 'breakfast',
    standardUnit: '1 dosa',
    calories: 155,
    protein_g: 4.5,
    carbohydrates_g: 26.0,
    fat_g: 3.5,
    fiber_g: 3.5,
    sugar_g: 0.4,
    sodium_mg: 180,
    isVeg: true,
  },
  {
    name: 'Idli',
    alternateNames: ['Idli with Sambar', 'Steamed Idli', 'Idly'],
    category: 'breakfast',
    standardUnit: '1 idli (50g)',
    calories: 65,
    protein_g: 2.2,
    carbohydrates_g: 14.0,
    fat_g: 0.4,
    fiber_g: 1.2,
    sugar_g: 0.1,
    sodium_mg: 80,
    isVeg: true,
  },
  {
    name: 'Medu Vada',
    alternateNames: ['Vada', 'Urad Dal Vada'],
    category: 'breakfast',
    standardUnit: 'piece (60g)',
    calories: 175,
    protein_g: 5.5,
    carbohydrates_g: 18.0,
    fat_g: 9.5,
    fiber_g: 3.5,
    sugar_g: 0.5,
    sodium_mg: 210,
    isVeg: true,
  },
  {
    name: 'Upma',
    alternateNames: ['Rava Upma', 'Uppittu', 'Vegetable Upma'],
    category: 'breakfast',
    standardUnit: 'bowl (150g)',
    calories: 205,
    protein_g: 5.2,
    carbohydrates_g: 36.0,
    fat_g: 5.0,
    fiber_g: 3.0,
    sugar_g: 1.0,
    sodium_mg: 260,
    isVeg: true,
  },
  {
    name: 'Poha',
    alternateNames: ['Pohe', 'Flattened Rice', 'Atukulu', 'Aval'],
    category: 'breakfast',
    standardUnit: 'bowl (150g)',
    calories: 215,
    protein_g: 5.0,
    carbohydrates_g: 38.0,
    fat_g: 5.5,
    fiber_g: 3.2,
    sugar_g: 1.5,
    sodium_mg: 230,
    isVeg: true,
  },
  {
    name: 'Ragi Java',
    alternateNames: ['Ragi Malt', 'Finger Millet Porridge', 'Ragi Ambali'],
    category: 'breakfast',
    standardUnit: 'glass (250ml)',
    calories: 120,
    protein_g: 4.2,
    carbohydrates_g: 25.0,
    fat_g: 1.2,
    fiber_g: 4.5,
    sugar_g: 2.0,
    sodium_mg: 60,
    isVeg: true,
  },
  {
    name: 'Ragi Mudde',
    alternateNames: ['Ragi Ball', 'Ragi Sankati'],
    category: 'grain',
    standardUnit: '1 ball (150g)',
    calories: 210,
    protein_g: 5.5,
    carbohydrates_g: 42.0,
    fat_g: 1.5,
    fiber_g: 5.8,
    sugar_g: 0.5,
    sodium_mg: 40,
    isVeg: true,
  },

  // 3. Rice, Dals & Curries
  {
    name: 'Rice',
    alternateNames: ['Steamed Rice', 'White Rice', 'Cooked Rice', 'Chawal'],
    category: 'grain',
    standardUnit: 'bowl (150g)',
    calories: 195,
    protein_g: 4.0,
    carbohydrates_g: 43.0,
    fat_g: 0.5,
    fiber_g: 0.6,
    sugar_g: 0.1,
    sodium_mg: 5,
    isVeg: true,
  },
  {
    name: 'Dal',
    alternateNames: ['Yellow Dal', 'Dal Tadka', 'Moong Dal', 'Toor Dal', 'Daal', 'Lentils'],
    category: 'pulse',
    standardUnit: 'bowl (150g)',
    calories: 145,
    protein_g: 9.0,
    carbohydrates_g: 22.0,
    fat_g: 2.5,
    fiber_g: 6.0,
    sugar_g: 1.0,
    sodium_mg: 280,
    isVeg: true,
  },
  {
    name: 'Sambar',
    alternateNames: ['South Indian Sambar', 'Lentil Stew'],
    category: 'pulse',
    standardUnit: 'bowl (150g)',
    calories: 115,
    protein_g: 5.5,
    carbohydrates_g: 18.0,
    fat_g: 2.5,
    fiber_g: 4.5,
    sugar_g: 2.5,
    sodium_mg: 310,
    isVeg: true,
  },
  {
    name: 'Rasam',
    alternateNames: ['Tomato Rasam', 'Pepper Rasam', 'Saaru'],
    category: 'soup',
    standardUnit: 'cup (150ml)',
    calories: 60,
    protein_g: 2.0,
    carbohydrates_g: 9.0,
    fat_g: 1.8,
    fiber_g: 1.5,
    sugar_g: 2.0,
    sodium_mg: 240,
    isVeg: true,
  },
  {
    name: 'Curd',
    alternateNames: ['Plain Dahi', 'Yogurt', 'Curds', 'Thayir'],
    category: 'dairy',
    standardUnit: 'cup (150g)',
    calories: 98,
    protein_g: 5.0,
    carbohydrates_g: 7.0,
    fat_g: 6.0,
    fiber_g: 0,
    sugar_g: 6.5,
    sodium_mg: 65,
    isVeg: true,
  },
  {
    name: 'Vegetable Curry',
    alternateNames: ['Mix Veg Curry', 'Subzi', 'Sabji', 'Mixed Vegetables'],
    category: 'vegetable',
    standardUnit: 'bowl (150g)',
    calories: 110,
    protein_g: 2.8,
    carbohydrates_g: 14.0,
    fat_g: 4.5,
    fiber_g: 4.2,
    sugar_g: 3.5,
    sodium_mg: 290,
    isVeg: true,
  },
  {
    name: 'Chicken Curry',
    alternateNames: ['Indian Chicken Curry', 'Murgh Kari'],
    category: 'curry',
    standardUnit: 'bowl (150g)',
    calories: 245,
    protein_g: 24.0,
    carbohydrates_g: 6.0,
    fat_g: 14.0,
    fiber_g: 1.5,
    sugar_g: 2.0,
    sodium_mg: 380,
    isVeg: false,
  },
  {
    name: 'Biryani',
    alternateNames: ['Chicken Biryani', 'Hyderabadi Biryani', 'Dum Biryani'],
    category: 'rice',
    standardUnit: 'plate (250g)',
    calories: 480,
    protein_g: 28.0,
    carbohydrates_g: 56.0,
    fat_g: 15.5,
    fiber_g: 3.5,
    sugar_g: 2.0,
    sodium_mg: 450,
    isVeg: false,
  },
  {
    name: 'Pulihora',
    alternateNames: ['Tamarind Rice', 'Puliyodarai', 'Chintapandu Pulihora'],
    category: 'rice',
    standardUnit: 'bowl (150g)',
    calories: 235,
    protein_g: 4.5,
    carbohydrates_g: 44.0,
    fat_g: 5.5,
    fiber_g: 2.2,
    sugar_g: 1.5,
    sodium_mg: 260,
    isVeg: true,
  },
  {
    name: 'Pongal',
    alternateNames: ['Ven Pongal', 'Khara Pongal'],
    category: 'rice',
    standardUnit: 'bowl (200g)',
    calories: 270,
    protein_g: 7.5,
    carbohydrates_g: 44.0,
    fat_g: 8.5,
    fiber_g: 3.5,
    sugar_g: 0.5,
    sodium_mg: 280,
    isVeg: true,
  },

  // 4. Breads & Rotis
  {
    name: 'Roti',
    alternateNames: ['Chapati', 'Phulka', 'Whole Wheat Roti', 'Chapatti'],
    category: 'grain',
    standardUnit: 'piece (35g)',
    calories: 85,
    protein_g: 3.1,
    carbohydrates_g: 16.0,
    fat_g: 0.5,
    fiber_g: 2.8,
    sugar_g: 0.3,
    sodium_mg: 60,
    isVeg: true,
  },
  {
    name: 'Paratha',
    alternateNames: ['Aloo Paratha', 'Plain Paratha', 'Parotta'],
    category: 'grain',
    standardUnit: '1 paratha (100g)',
    calories: 260,
    protein_g: 5.8,
    carbohydrates_g: 38.0,
    fat_g: 10.0,
    fiber_g: 3.5,
    sugar_g: 1.0,
    sodium_mg: 240,
    isVeg: true,
  },
  {
    name: 'Puri',
    alternateNames: ['Poori', 'Fried Bread'],
    category: 'grain',
    standardUnit: 'piece (30g)',
    calories: 120,
    protein_g: 2.2,
    carbohydrates_g: 16.0,
    fat_g: 5.5,
    fiber_g: 1.2,
    sugar_g: 0.2,
    sodium_mg: 70,
    isVeg: true,
  },

  // 5. Protein, Fruits & Vegetables
  {
    name: 'Egg',
    alternateNames: ['Boiled Egg', 'Cooked Egg', 'Anda', 'Whole Egg'],
    category: 'protein',
    standardUnit: 'piece (50g)',
    calories: 74,
    protein_g: 6.3,
    carbohydrates_g: 0.4,
    fat_g: 5.0,
    fiber_g: 0,
    sugar_g: 0.4,
    sodium_mg: 62,
    isVeg: false,
  },
  {
    name: 'Paneer',
    alternateNames: ['Cottage Cheese', 'Paneer Tikka', 'Raw Paneer'],
    category: 'protein',
    standardUnit: 'serving (100g)',
    calories: 265,
    protein_g: 18.0,
    carbohydrates_g: 3.5,
    fat_g: 20.0,
    fiber_g: 0,
    sugar_g: 2.5,
    sodium_mg: 18,
    isVeg: true,
  },
  {
    name: 'Apple',
    alternateNames: ['Fresh Apple', 'Red Apple'],
    category: 'fruit',
    standardUnit: '1 medium (150g)',
    calories: 95,
    protein_g: 0.5,
    carbohydrates_g: 25.0,
    fat_g: 0.3,
    fiber_g: 4.4,
    sugar_g: 19.0,
    sodium_mg: 2,
    isVeg: true,
  },
  {
    name: 'Banana',
    alternateNames: ['Ripe Banana', 'Kela'],
    category: 'fruit',
    standardUnit: '1 medium (118g)',
    calories: 105,
    protein_g: 1.3,
    carbohydrates_g: 27.0,
    fat_g: 0.4,
    fiber_g: 3.1,
    sugar_g: 14.0,
    sodium_mg: 1,
    isVeg: true,
  },
  {
    name: 'Sprouts',
    alternateNames: ['Sprouted Moong', 'Moong Sprouts', 'Bean Sprouts'],
    category: 'protein',
    standardUnit: 'bowl (100g)',
    calories: 105,
    protein_g: 7.8,
    carbohydrates_g: 18.0,
    fat_g: 0.6,
    fiber_g: 5.2,
    sugar_g: 2.0,
    sodium_mg: 12,
    isVeg: true,
  },
];

/**
 * Find nutritional data for a food name, checking primary and alternate names.
 */
export const findNutritionInDatabase = (foodName = '') => {
  if (!foodName || typeof foodName !== 'string') return null;
  const q = foodName.trim().toLowerCase();

  // Exact match first
  let match = NUTRITION_DATABASE.find(f => f.name.toLowerCase() === q);
  if (match) return { ...match, matchType: 'exact' };

  // Alternate names exact match
  match = NUTRITION_DATABASE.find(f =>
    f.alternateNames && f.alternateNames.some(alt => alt.toLowerCase() === q)
  );
  if (match) return { ...match, matchType: 'alternate' };

  // Partial substring match
  match = NUTRITION_DATABASE.find(f =>
    q.includes(f.name.toLowerCase()) || f.name.toLowerCase().includes(q)
  );
  if (match) return { ...match, matchType: 'partial' };

  // Alternate names partial match
  match = NUTRITION_DATABASE.find(f =>
    f.alternateNames && f.alternateNames.some(alt => q.includes(alt.toLowerCase()) || alt.toLowerCase().includes(q))
  );
  if (match) return { ...match, matchType: 'partial_alternate' };

  return null;
};

/**
 * STAGE 5: NUTRITION SERVICE
 * Calculates estimated nutrition for an item or a set of items based on database lookup and portion multiplier.
 */
export const calculateFoodNutrition = ({
  foodName,
  quantity = 1,
  unit = 'serving',
  brand = null,
  barcode = null,
}) => {
  const dbItem = findNutritionInDatabase(foodName);

  if (!dbItem) {
    return {
      name: foodName,
      quantity: Number(quantity) || 1,
      unit,
      nutrition: {
        calories: null,
        protein_g: null,
        carbohydrates_g: null,
        fat_g: null,
        fiber_g: null,
        sugar_g: null,
        sodium_mg: null,
      },
      nutritionSource: 'estimate',
      isReliable: false,
      message: 'Nutrition information could not be reliably determined for this food.',
    };
  }

  const qty = Math.max(0.25, Number(quantity) || 1);

  return {
    name: dbItem.name,
    category: dbItem.category,
    quantity: Math.round(qty * 10) / 10,
    unit: unit || dbItem.standardUnit,
    nutrition: {
      calories: Math.round(dbItem.calories * qty),
      protein_g: Math.round(dbItem.protein_g * qty * 10) / 10,
      carbohydrates_g: Math.round(dbItem.carbohydrates_g * qty * 10) / 10,
      fat_g: Math.round(dbItem.fat_g * qty * 10) / 10,
      fiber_g: Math.round(dbItem.fiber_g * qty * 10) / 10,
      sugar_g: Math.round((dbItem.sugar_g || 0) * qty * 10) / 10,
      sodium_mg: Math.round((dbItem.sodium_mg || 0) * qty),
    },
    nutritionSource: 'database',
    isReliable: true,
  };
};

/**
 * Calculates total nutrition across multiple detected food items in a meal.
 */
export const calculateMealTotals = (items = []) => {
  return items.reduce((acc, item) => {
    const nut = item.nutrition || {};
    return {
      calories: acc.calories + (Number(nut.calories) || 0),
      protein_g: Math.round((acc.protein_g + (Number(nut.protein_g) || 0)) * 10) / 10,
      carbohydrates_g: Math.round((acc.carbohydrates_g + (Number(nut.carbohydrates_g) || 0)) * 10) / 10,
      fat_g: Math.round((acc.fat_g + (Number(nut.fat_g) || 0)) * 10) / 10,
      fiber_g: Math.round((acc.fiber_g + (Number(nut.fiber_g) || 0)) * 10) / 10,
      sugar_g: Math.round((acc.sugar_g + (Number(nut.sugar_g) || 0)) * 10) / 10,
      sodium_mg: Math.round((acc.sodium_mg + (Number(nut.sodium_mg) || 0))),
    };
  }, {
    calories: 0,
    protein_g: 0,
    carbohydrates_g: 0,
    fat_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
  });
};
